version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14.x
    commands:
      - npm install -g aws-cli

  build:
    commands:
      - npm install
      - zip -r lambda_function.zip index.js node_modules/

  post_build:
    commands:
      - echo "Deploying Lambda Function..."
      - aws lambda update-function-code --function-name github-to-lambda-demo --zip-file fileb://lambda_function.zip
      - echo "Lambda Function deployment completed!"
